from typing import Self

from pydantic import BaseModel, Field

from src.schemas import (
    QualifiedEvent,
    QualifiedEvents,
    Script,
    EnhancedScript,
    ScriptImagePrompts,
    ImagePrompt,
    Events,
    StoryBoard,
    VisualLookbook,
    SceneIllustrated,
    ScenesIllustrated,
    ScenesAnimated
)

AppEvents = Events
AppQualifiedEvent = QualifiedEvent
AppQualifiedEvents = QualifiedEvents
AppScript = Script
AppSrcScriptImagePrompts = ScriptImagePrompts
AppSrcImagePrompt = ImagePrompt
AppEnhancedScript = EnhancedScript
AppStoryBoard = StoryBoard
AppScenesAnimated = ScenesAnimated

class AppGeneratedScript(BaseModel):
    script: AppScript
    temperature: float

class AppHook(BaseModel):
    hook: str = Field(..., description="The hook generated by the model.")
    temperature: float
    scripts: list[AppGeneratedScript] | None = Field(default=None)

class AppHooks(BaseModel):
    hooks: list[AppHook]
    selected_script_index: tuple[int,int] | None = Field(description="The index of the selected script.", default=None)

class AppPromptImproved(BaseModel):
    prompt: str = Field(..., description="The improved prompt to generate the image with Imagen to display with this script segment.")
    negative_prompt: str = Field(..., description="The negative prompt to generate the image with Imagen to display with this script segment.")

class AppImagePrompt(BaseModel):
    prompt: str = Field(..., description="The prompt to generate the image with Imagen to display with this script segment.")
    negative_prompt: str | None = Field(description="The negative prompt to generate the image with Imagen to display with this script segment.", default=None)
    images_path: list[str] = Field(description="The list of paths to the images generated from the prompt.", default = [])

class AppImagesPrompts(BaseModel):
    script_segment: str = Field(..., description="The script segment.")
    image_prompts: list[AppImagePrompt]
    selected_image_path: str | None = Field(description="The path of the selected image.", default = None)

class AppScriptImagesPrompts(BaseModel):
    image_prompts: list[AppImagesPrompts] | None = Field(default=None)

    @classmethod
    def from_script_image_prompts(cls, image_prompts: ScriptImagePrompts) -> Self:
        return AppScriptImagesPrompts(
            image_prompts=\
            [
                AppImagesPrompts(
                    script_segment=prompt.script_segment,
                    image_prompts=[
                        AppImagePrompt(
                            prompt=prompt.prompt,
                            negative_prompt=prompt.negative_prompt
                        )
                    ]
                )
                for prompt in image_prompts.image_prompts]
        )

    def to_script_image_prompts(self, indices: list[int]) -> ScriptImagePrompts:
        return ScriptImagePrompts(
            image_prompts=[
                AppSrcImagePrompt(
                    prompt=self.image_prompts[i].image_prompts[
                        indices[i]].prompt,
                    negative_prompt=self.image_prompts[i].image_prompts[
                        indices[i]].negative_prompt,
                    script_segment=self.image_prompts[i].script_segment,
                )
                for i in range(len(self.image_prompts))
            ]
        )

    def get_selected_image_filepath(self, index: int) -> str:
        return self.image_prompts[index].selected_image_path

class AppStoryBoards(BaseModel):
    storyboards: list[AppStoryBoard]
    selected_storyboard_index: int | None = Field(description="The index of the selected storyboard.", default=None)
    lookbook: VisualLookbook | None

class AppScenesIllustrated(ScenesIllustrated):

    @classmethod
    def from_storyboard_image_prompts(cls, storyboard: StoryBoard, image_prompts=AppScriptImagesPrompts) -> Self:
        scenes = []
        for i in range(len(storyboard.scenes)):
            script_segment = storyboard.scenes[i].script_segment
            visual_description = storyboard.scenes[i].visual_description

            scene_image_prompts = image_prompts.image_prompts[i]
            selected_path = scene_image_prompts.selected_image_path
            prompt = [
                scene_image_prompts.image_prompts[k].prompt
                for k in range(len(scene_image_prompts.image_prompts))
                if selected_path in scene_image_prompts.image_prompts[k].images_path
            ][0]
            negative_prompt = [
                scene_image_prompts.image_prompts[k].negative_prompt
                for k in range(len(scene_image_prompts.image_prompts))
                if selected_path in scene_image_prompts.image_prompts[k].images_path
            ][0]

            scenes.append(
                SceneIllustrated(
                    script_segment=script_segment,
                    visual_description=visual_description,
                    prompt=prompt,
                    negative_prompt=negative_prompt,
                )
            )

        return AppScenesIllustrated(
            scenes=scenes
        )